### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by deveshks** [toxicaker/ltcd4vip#3]
The website http://leetcode.liangjiateng.cn/leetcode/algorithm seems to have been down since a past few days with 502 Bad Gateway Error. 

When can we expect for the website to come back up?

**Comment by toxicaker** [comment]
Hi,


Sorry I cannot resume the website since it's kind of controversial and I have been warned. If you want to see locked problem. Please refer to&nbsp;https://github.com/toxicaker/job_shceduler/blob/master/job/leetcode_problem.py&nbsp;


Jiateng






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Devesh Kumar Singh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 凌晨3:04
收件人:&nbsp;"toxicaker/ltcd4vip"<ltcd4vip@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[toxicaker/ltcd4vip] Website down (#3)




The website http://leetcode.liangjiateng.cn/leetcode/algorithm seems to have been down since a past few days with 502 Bad Gateway Error.
 
When can we expect for the website to come back up?

**Comment by deveshks** [comment]
Thanks for the response @toxicaker 

Are there any instructions on how to use that python file?

**Comment by toxicaker** [comment]
1. download this repo&nbsp;https://github.com/toxicaker/job_shceduler&nbsp;
2. create a mysql database and create the tables:&nbsp;https://github.com/toxicaker/job_shceduler/blob/master/sql/create_table.sql
3. set mysql database connection:&nbsp;https://github.com/toxicaker/job_shceduler/blob/master/config/config_test.py&nbsp;(DB_URL_CONNECTION)
4. run `python3 leetcode_problem.py`&nbsp;https://github.com/toxicaker/job_shceduler/blob/master/job/leetcode_problem.py
5. web ui:&nbsp;https://github.com/toxicaker/ltcd4vip
&nbsp;

Jadyn Liang&nbsp;(梁嘉腾)
School of Information and Software Engineering
University of Electronic Science and Technology of China
Personal page



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Devesh Kumar Singh"<notifications@github.com&gt;; 
发送时间: 2020年1月16日(星期四) 凌晨3:28
收件人: "toxicaker/ltcd4vip"<ltcd4vip@noreply.github.com&gt;; 
抄送: "梁嘉腾"<toxicaker@liangjiateng.cn&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [toxicaker/ltcd4vip] Website down (#3)




Thanks for the response @toxicaker
 
Are there any instructions on how to use that python file?

**Comment by deveshks** [comment]
Hi @toxicaker 
I did the steps 1,2 and 3, but when I run command 4, I get the error as follows

```
$ python leetcode_problem.py 
Traceback (most recent call last):
  File "leetcode_problem.py", line 7, in <module>
    from common.db import session, engine
ModuleNotFoundError: No module named 'common'
```
How can I resolve it?

**Comment by toxicaker** [comment]
web ui: http://206.81.6.248:12306/leetcode/algorithm

**Comment by toxicaker** [comment]
I think `No module named common` is not my script's problem. It's a common issue related to your IDE setting.

**Comment by deveshks** [comment]
Yes I do see that common is another folder in the repo, how can I make sure that common is imported when I run `python leetcode_problem.py` ?  I am using latest code from master branch for job_shceduler and using PyCharm IDE

**Comment by toxicaker** [comment]
![image](https://user-images.githubusercontent.com/11787200/72686436-bcd23c00-3aa9-11ea-862a-4dac5bf014b3.png)

right click root dir, mark as source root. Then try to run it by using IDE

**Comment by deveshks** [comment]
Thank you. I was able to run it using the IDE, but what credentials should I be using to connect so that your website is rendered as before? Are the username/password provided in `leetcode_problem.py` correct?

**Comment by toxicaker** [comment]
Of course that's a fake account...

**Comment by deveshks** [comment]
Ohh okay, Were you using like a common premium account or your own account in order to pull data and then post it on the website. 

Unfortunately I do not own a premium account currently to do the same.

**Comment by toxicaker** [comment]
You may subscribe once or borrow an account and save the data to your DB. Then you don't have to subscribe it. I am not premium either now.

**Comment by deveshks** [comment]
Thanks. I unfortunately don't know anyone from whom to borrow. But thanks for the help

**Comment by shahidul-brur** [comment]
Hello @toxicaker. Can you share the db data that you had stored in db when you had premium account, so that one can import that data in his db if he has no premium account? Or is there any other way to access the premium problems without having a premium account?
